### ISSUE TITLE
Test whether it is possible to use React with an Angular codebase

### ISSUE THREAD

**Issue by maboa** [meedan/montage#1]
@laurian is looking into this. He wrote on Slack:

> 
> OK, using an Angular 1.x sample https://github.com/zxbodya/angular-webpack-seed I tested that I can have with https://github.com/coatue-oss/react2angular my own React component rendered in an Angular template while Angular was passing values to the React component props.
> I used a webpack based sample as I wanted to toy within the same build system and have at least some ES6 support; however the defaults on that sample did not enjoy JSX but we will anyway create our React components in another repo and npm install them as deps, so no need for any fancy webpack or JSX support in the legacy app.
> It is quite fun when you have a `class MyComponent extends React.Component` attached to an Angular module and rendered with `<my-component foo="item.title"></my-component>` inside an ng-repeat loop

https://meedan.slack.com/archives/CBTP2L8Q5/p1533597477000070?thread_ts=1533056915.000223&cid=CBTP2L8Q5

**Comment by infojunkie** [comment]
hola!

**Comment by infojunkie** [comment]
I think that's been established, right?
