### ISSUE TITLE
Don't use browser-based authentication during deployment

### ISSUE THREAD

**Issue by infojunkie** [meedan/montage#10]
The current `grunt deployProd` task (and possibly others) requires the user to login to a Google account via the browser. This prevents the deployment from happening in headless environments such as Docker or Jenkins. We need to fix the deployment process for all stages such that it uses API keys and tokens instead of user login.

**Comment by infojunkie** [comment]
Have the tasks use `gcloud` if possible.

**Comment by Ahmid** [comment]
We can deploy new versions of the app using `gcloud`, this does not require a browser-based authentication. 
For example, for deploying a new version of `Montage` we can use the following:

`gcloud app deploy app.yaml publisher.yaml worker.yaml long-poller.yaml --no-promote --project greenday-project --version 3-0-26` 

`.yaml`: services that Montage uses.
`no-promote`: When deploying a new version, by default the traffic will be 100% allocated to it. However we should first test if the new version is deployed successfully so we use --no-promote to prevent allocation the traffic and do it manually when we are good.

**Comment by infojunkie** [comment]
Good to know that `gcloud` can be used. We need to keep using `grunt deployXXXX` for deployment, though. This present ticket is about changing `grunt deployXXX` tasks to use `gcloud` instead of its current mechanism of deployment, making sure that other functionalities of the `grunt` deployment tasks remain as is.

**Comment by Ahmid** [comment]
Ok got it. Need to know where are we using grunt for `grunt deployXXXX` so I can start checking using `gcloud` instead .

**Comment by caiosba** [comment]
Done. I'm now using `gcloud` (which is installed in the Docker container during `docker-compose build`) and authenticating using an API key. We just need to download a JSON keys file from Google Cloud (for a user account or services account) and place it at `appengine/auth.json`. There is a `appengine/auth.json.example` that explains how to get one. I also added a `npm run authenticate` command that performs the headless authentication. After that, we can run any other task using `gcloud` command. I'm using this for the deployment ( #6 ).
