### ISSUE TITLE
Get GCP app verified

### ISSUE THREAD

**Issue by infojunkie** [meedan/montage#12]
The current GCP app is not "verified", as per https://developers.google.com/apps-script/guides/client-verification and shows the attached warning which needs to be fixed.
<img width="637" alt="egftonpksm2emhpa0c3i_full_screen shot 2018-08-10 at 10 14 04 am" src="https://user-images.githubusercontent.com/92977/44104962-15e98966-9fa5-11e8-9e0b-8f9bb2eb513a.png">

**Comment by infojunkie** [comment]
I submitted the request at the beginning of the week but haven't heard back. Will ping them on Monday.

**Comment by infojunkie** [comment]
Looks like it's done now... Need confirmation.

**Comment by infojunkie** [comment]
Several users have confirmed thay are still getting the warning.

**Comment by infojunkie** [comment]
At least one user is seeing this screen instead, that is preventing login altogether. 
<img width="559" alt="screenshot_2018-08-28_at_18 38 20 1" src="https://user-images.githubusercontent.com/92977/44737953-442fa180-aaa8-11e8-8025-435a1c228fce.png">

**Comment by infojunkie** [comment]
I confirm that when I removed the Montage app permission for my own account at https://myaccount.google.com/permissions, and tried to login Montage again, I was shown the above error.

**Comment by infojunkie** [comment]
Submitted a new application form with updated PP, ToS, adjusted scopes.

**Comment by infojunkie** [comment]
I had submitted the wrong key :sob: - resubmitting now. Should this happen again, here's the scope information:
```
email: send user email notifications
profile: display user name
https://www.googleapis.com/auth/youtube.readonly: search for videos, get video information
https://www.googleapis.com/auth/contacts.readonly: allow user to invite their contacts to use the app
```

**Comment by infojunkie** [comment]
Had to verify ownership of the domain https://greenday-project.appspot.com - done.

**Comment by infojunkie** [comment]
>The Google sign-in button on your app’s homepage URL https://montage.meedan.com  is not compliant with the [Google sign-in branding guidelines](https://developers.google.com/identity/branding-guidelines). Please update the Google sign-in button on your website according to the Google sign-in branding guidelines and then reply back to this email.

**Comment by infojunkie** [comment]
Could use the help of @makaelastephens here. Here's the button we need to redesign: 
![screenshot-montage meedan com-2018 09 01-08-40-57](https://user-images.githubusercontent.com/92977/44947519-e9a58680-adc2-11e8-8de3-8f79b534b95f.png)
Note that we do use a YouTube scope, so YouTube branding guidelines also apply.

**Comment by makaelastephens** [comment]
If I understand correctly, we just need to use the button contained in the ZIP folder this link mentions: https://developers.google.com/identity/branding-guidelines

The button:
https://developers.google.com/identity/images/signin-assets.zip
(We should just use light)

Based on https://developers.google.com/youtube/terms/branding-guidelines it looks like we also need a "Developed with YouTube logo". 

> You should use a developed with YouTube logo if removing YouTube functionality from your application would render the application nonfunctional or not useful.

**Comment by infojunkie** [comment]
Fixed the brading as per attached screenshot. Re-submitted the app for review.
![screenshot-montage meedan com-2018 09 05-17-50-21](https://user-images.githubusercontent.com/92977/45128679-3a570f80-b134-11e8-8b46-fcdffebbbe11.png)

**Comment by infojunkie** [comment]
App has been approved :dancer:

**Comment by infojunkie** [comment]
Now it's confirmed working.

**Comment by infojunkie** [comment]
Note that any change to the client ID will need a re-submission OR an update request https://support.google.com/code/contact/oauth_app_update @caiosba
