### ISSUE TITLE
Undefined JavaScript variables in local mode

### ISSUE THREAD

**Issue by caiosba** [meedan/montage#15]
When running Montage locally, we see warning about undefined variables `FS` and `heap`.

**Comment by caiosba** [comment]
This happens because `FS` and `heap` are only enabled in production mode, but the code assumes that they are always available. Fixed by checking first if they are defined.

**Comment by caiosba** [comment]
Pushed a fix to `develop`.

**Comment by infojunkie** [comment]
I confirm that I no longer see the `heap` exception in the JS console.
