### ISSUE TITLE
Infinite load when inviting collaborator, never actually sends

### ISSUE THREAD

**Issue by makaelastephens** [meedan/montage#25]
Using iMac 2015 and Chrome Version 67.0.3396.99.

I type an email address to invite them as a collaborator for my project. 
The loading animation continues to loop. No change.
If I refresh the browser and click the "Invite" icon again, it now says "Awaiting response" for the email address I entered.
I never get an invitation to the address entered (checked junk mail)

<img width="2079" alt="screen shot 2018-08-22 at 3 20 09 pm" src="https://user-images.githubusercontent.com/33822068/44494183-a8bdad00-a61f-11e8-99f9-9ff81520d386.png">

<img width="2074" alt="screen shot 2018-08-22 at 3 20 23 pm" src="https://user-images.githubusercontent.com/33822068/44494182-a8251680-a61f-11e8-9d35-806c0ca882cf.png">

**Comment by infojunkie** [comment]
related to #24

**Comment by infojunkie** [comment]
Fixed, plz test
