### ISSUE TITLE
Ensure Google+ APIs are not used

### ISSUE THREAD

**Issue by caiosba** [meedan/montage#36]
On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019.

In our case, we're using it in one place: https://github.com/meedan/montage/blob/develop/appengine/src/greenday_public/static-dev/js/services/user.service.js#L190.

**Comment by mhamzawey** [comment]
@caiosba I found a couple of `google_plus_profile` as of https://github.com/meedan/montage/blob/b63219fc31d4889f908fff7f98b20152c19a154a/appengine/src/greenday_public/static-dev/js/services/user.service.js#L178 

and we are depending on it in this if statement
https://github.com/meedan/montage/blob/b63219fc31d4889f908fff7f98b20152c19a154a/appengine/src/greenday_public/static-dev/js/services/user.service.js#L188

Do we depend on google plus profile heavily? 

regarding this:
https://github.com/meedan/montage/blob/b63219fc31d4889f908fff7f98b20152c19a154a/appengine/src/greenday_public/static-dev/js/services/user.service.js#L190 

I am not familiar with google plus apis, but can you please let me know if we followed [this](https://stackoverflow.com/questions/7130648/get-user-info-via-google-api)  It might fix it?

**Comment by caiosba** [comment]
@mhamzawey AFAIK we call Google Plus API in order to get user information to be saved in his profile. I think a good approach for this issue is to try to find out which information we get today from Google Plus (e.g., by inspecting what is returned by https://github.com/meedan/montage/blob/b63219fc31d4889f908fff7f98b20152c19a154a/appengine/src/greenday_public/static-dev/js/services/user.service.js#L190), how we save it in the profile and then replace it by the equivalent call to the new Google API, as per the last link you pasted. I had to do something similar before to replace OAuth 1 by OAuth 2.

**Comment by infojunkie** [comment]
Regarding the G+ URL, I am noticing it still exists: https://plus.google.com/u/1/103893092845072915208 - so where can we find it?

**Comment by infojunkie** [comment]
Good to know, thanks for testing. The last thing to answer here before we can deploy this to live is:
> Regarding the G+ URL, I am noticing it still exists: https://plus.google.com/u/1/103893092845072915208 - so where can we find it?

**Comment by mhamzawey** [comment]
@infojunkie done. let me know if we can merge that to `develop`

**Comment by mhamzawey** [comment]
@infojunkie everything looks fine on my end.  

Please check before merging to `master`

**Comment by infojunkie** [comment]
The changes here have broken a number of frontend tests (`npm run test:frontend`). Fixing before I merge to `master`.

**Comment by infojunkie** [comment]
Deployed live!
