### ISSUE TITLE
Live deployment is broken

### ISSUE THREAD

**Issue by infojunkie** [meedan/montage#40]
As per https://jenkins.dev.meedan.com/job/montage-master/15/console, the db migration fails at:
```
[31m>> [39mconn = Database.connect(**conn_params)[31m
>> [39m  File "/app/GREENDAY/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect[31m
>> [39m    return Connection(*args, **kwargs)[31m
>> [39m  File "/app/GREENDAY/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__[31m
>> [39m    super(Connection, self).__init__(*args, **kwargs2)[31m
>> [39mdjango.db.utils.OperationalError: (2026, 'SSL connection error: SSL_CTX_set_default_verify_paths failed')
```
The QA migration works fine.

To debug locally:
- Add your local IP to *Authorized networks* at https://console.cloud.google.com/sql/instances/v2/connections?project=greenday-project
- Download the *deployment* SSL certs from *Configure SSL client certificates* on the same page
- Attempt to connect from your local mysql client using the certs above: https://dev.mysql.com/doc/refman/5.7/en/encrypted-connection-options.html

**Comment by infojunkie** [comment]
I'm noticing this on the *IP Address* tab of the SQL instance:
```
IPv6 address
Every First Generation Cloud SQL instance has an IPv6 address free of charge.

2001:4860:4864:1:522d:1480:358a:cb0c

IPv4 address
You will be charged $0.01 each hour the instance is inactive and has an IPv4 address assigned.

173.194.240.116
```

**Comment by infojunkie** [comment]
hello?

**Comment by caiosba** [comment]
Fixed. The paths to the SSL certs for live were wrong. I fixed them on this commit: https://github.com/meedan/montage/commit/8244b4342209d6119bf7feae46f3b3d462374c4e.
