### ISSUE TITLE
Google+ APIs and OAuth requests are being shutdown on March 7, 2019

### ISSUE THREAD

**Issue by infojunkie** [meedan/montage#41]
More deprecation:

> The email below contains your most recent usage of Google+ APIs. Note: It includes Google+ OAuth scope requests, which are also affected by the Google+ shutdown. A prior email sent to active API callers did not include information about OAuth requests. One final reminder email will be sent in February to users who still have active API or OAuth request activity.
> 
> What do I need to know?
> On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown, with API calls starting to intermittently fail as early as January 28, 2019, and OAuth requests for Google+ scopes starting to intermittently fail as early as February 15, 2019.
> 
> What do I need to do?
> Please update your projects listed below by March 7, 2019 and ensure they are no longer using Google+ APIs, or requesting Google+ OAuth scopes. The data below shows which Google+ API methods your projects have recently called, as well as Google+ OAuth scopes it has requested.
> 
> Note: If you see calls to people.get, these can be the result of using the Google+ Sign-In feature in your application, which is now fully deprecated and is being shut down. Developers should migrate from the Google+ Sign-In feature to the more comprehensive Google Sign-in authentication system.
> 
> 
> Project | Google+ API Name | Version | Method or OAuth Scope
> Montage (greenday-project) | plus | v1 | plus.people.get
> Montage (greenday-project) | OAuth | N/A | plus.me
> 
> Anything else to know?
> Google+ integrations for web or mobile apps are also being shut down. Please see this additional notice.
>

**Comment by mhamzawey** [comment]
Disabled G+ API from the GCC and tested on both QC and Live and things are working fine.

Will keep this under observation for a couple of days to guarantee  that things are stable.
@infojunkie

**Comment by infojunkie** [comment]
Received an email update from Google:

> Earlier this week we sent you an email related to your projects that will be impacted by the Google+ API shutdown, which also affects requests for Google+ OAuth scopes.
> 
> The email listed that one or more of your projects are requesting the “plus.me” scope, and would thus be affected. We would like to clarify that only projects directly requesting the “plus.me” scope are affected. This scope may have been listed in some emails, even if not directly requested by your project. We apologize for any confusion caused.
> 
> If you are directly requesting the “plus.me” scope, any other Google+ OAuth scopes, or making any Google+ API calls, please ensure that you remove these requests from your project before March 7, 2019.
> 
> To see if your project is directly requesting the “plus.me” or any other Google+ OAuth scopes:
> 
> If your project is written in Google Apps Script, you can view which scopes your project is requesting by reviewing your project properties in App Script Editor.
> If your project is not written in Google Apps Script, please check your code for references to “plus.me” in OAuth scope requests. We recommend that you review projects using any 3rd-party libraries that support sign-in or social functionality, as these may also be affected by the shutdown.

Our app does not request `plus.me` or any G+ scope afaict: https://github.com/meedan/montage/blob/develop/appengine/src/greenday_public/static-dev/js/services/app.services.module.js#L15-L19
